Release 1.0.0 to MASTER
snowplow/scala-weather pull request #130
Opened 2020-08-27 19:36 UTC by lukeindykiewicz

There are two more commits (already in master), that's why changelog shows more commits than there are commits in this PR.
Replace historic weather requests with current (close #125)
Update OpenWeatherMap credentials in travis.yml (close #123)

That's due to change to gitflow workflow in the middle of this "release"

2020-09-02 07:52 UTC, benjben requested changes
Looks good, just CHANGELOG and `Prepare for release` to update.

https://github.com/snowplow/scala-weather/pull/130/commits/5a764c13aef63fcb4206ed3d42267f3dc1c0403a contains some reformatting, do you have scalafmt enabled globally for your sbt?

2020-09-02 07:52 UTC, benjben commented on CHANGELOG
> +Update OpenWeatherMap credentials in travis.yml (close #123)
CHANGELOG should not contain `close`. Given that you're going to update it, please take the opportunity to update the release date.

2020-09-02 07:52 UTC, benjben commented on build.sbt
> +    version := "1.0.0",
This should happen in `Prepare for release` commit.

2020-09-02 18:04 UTC, lukeindykiewicz commented
> 5a764c1 contains some reformatting, do you have scalafmt enabled globally for your sbt?
I have format on save in my editor. 
That's the only way to have code formatted, but it accidetally makes this kind of things. I'll try to fix that.

2020-09-03 06:32 UTC, benjben approved these changes

2020-09-04 15:45 UTC, merged